### ISSUE TITLE
测试的输出图片没有框显示

### ISSUE THREAD

**Issue by By-he** [DataXujing/Faster-R-CNN-Keras#1]
作者您好，请问我按照您的方法执行了训练代码没有问题，epoch改为了10次，在运行测试代码的时候输出的图片没有边界框的显示，就是原图像的输出，请问这是为什么呢？也没有报错。

**Comment by DataXujing** [comment]
增加训练的epoch,如果仅从安全帽检测任务来说不建议使用Faster R-CNN, 因其对小目标检测并不是最优的。还有就是要人工调整一下anchor, 这里我设置的anchor并不是最优的。
